import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';

const PEAKS=[
 {id:'chavalard',name:'Grand Chavalard',elevation:2899,lat:46.17869,lon:7.11312,region:'Fully'},
 {id:'lagginhorn',name:'Lagginhorn',elevation:4010,lat:46.15706,lon:8.00310,region:'Saas-Grund'},
 {id:'jegihorn',name:'Jegihorn',elevation:3206,lat:46.20550,lon:7.95640,region:'Saas-Grund'},
 {id:'barrhorn',name:'Barrhorn',elevation:3610,lat:46.18030,lon:7.73580,region:'Turtmanntal'},
 {id:'bigerhorn',name:'Bigerhorn',elevation:3626,lat:46.19240,lon:7.76270,region:'Turtmanntal'},
 {id:'mettelhorn',name:'Mettelhorn',elevation:3406,lat:46.05510,lon:7.71680,region:'Zermatt'},
 {id:'rinderhorn',name:'Rinderhorn',elevation:3448,lat:46.44200,lon:7.65360,region:'Kandersteg'}
];
const MAX_PEAKS=3,ELEVATION_ZOOM=12,IMAGERY_ZOOM=13,TILE_SIZE=256;
const GRID=matchMedia('(max-width: 760px)').matches?80:112;
const BASE_Y=-.42,TILE_CACHE=new Map(),$=s=>document.querySelector(s);
let peaks=[...PEAKS],selected=['chavalard','lagginhorn'],blocks=[],gpxTrack=[],buildVersion=0,patchKm=12,exaggeration=1,shadowsEnabled=true,cloudTexture,sideMaterial,floor,rebuildTimer;

const canvas=$('#sceneCanvas'),stage=$('#stage');
const renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:true,powerPreference:'high-performance'});
renderer.setPixelRatio(Math.min(devicePixelRatio,matchMedia('(max-width: 760px)').matches?1.6:2));
renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.08;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;
const scene=new THREE.Scene();scene.fog=new THREE.FogExp2(0x142631,.013);
const camera=new THREE.PerspectiveCamera(37,1,.1,240),controls=new OrbitControls(camera,canvas);
controls.enableDamping=true;controls.dampingFactor=.055;controls.minDistance=7;controls.maxDistance=110;controls.maxPolarAngle=Math.PI*.485;controls.autoRotateSpeed=.48;
scene.add(new THREE.HemisphereLight(0xcce9f4,0x16202a,1.7));
const sun=new THREE.DirectionalLight(0xffefd3,3.3);sun.position.set(-18,28,16);sun.castShadow=true;const shadowSize=matchMedia('(max-width: 760px)').matches?1024:2048;sun.shadow.mapSize.set(shadowSize,shadowSize);sun.shadow.camera.near=1;sun.shadow.camera.far=100;sun.shadow.camera.left=-45;sun.shadow.camera.right=45;sun.shadow.camera.top=30;sun.shadow.camera.bottom=-30;sun.shadow.bias=-.00025;scene.add(sun);
const rim=new THREE.DirectionalLight(0x76c9ed,1.25);rim.position.set(22,9,-20);scene.add(rim);

setupEnvironment();renderPeakList();restoreStats();bindControls();resize();rebuildScene();requestAnimationFrame(animate);

function activePeaks(){return selected.map(id=>peaks.find(p=>p.id===id)).filter(Boolean)}
function setupEnvironment(){const floorTexture=makeGroundTexture(),floorMaterial=new THREE.MeshStandardMaterial({map:floorTexture,color:0x6b7271,roughness:.92,metalness:0});floor=new THREE.Mesh(new THREE.PlaneGeometry(180,120),floorMaterial);floor.rotation.x=-Math.PI/2;floor.position.y=BASE_Y-.035;floor.receiveShadow=true;scene.add(floor);cloudTexture=makeCloudTexture();sideMaterial=new THREE.MeshStandardMaterial({map:makeStoneTexture(),color:0x7e7669,roughness:1,metalness:0,side:THREE.DoubleSide})}
function makeGroundTexture(){const c=document.createElement('canvas');c.width=c.height=512;const ctx=c.getContext('2d'),g=ctx.createLinearGradient(0,0,512,512);g.addColorStop(0,'#48545a');g.addColorStop(.5,'#2e3c43');g.addColorStop(1,'#202e35');ctx.fillStyle=g;ctx.fillRect(0,0,512,512);const rng=seededRandom(8821);for(let i=0;i<1100;i++){ctx.fillStyle=`rgba(220,235,237,${rng()*.055})`;const x=rng()*512,y=rng()*512,r=.3+rng()*1.2;ctx.fillRect(x,y,r,r)}const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;t.wrapS=t.wrapT=THREE.RepeatWrapping;t.repeat.set(7,5);return t}
function makeStoneTexture(){const c=document.createElement('canvas');c.width=c.height=512;const ctx=c.getContext('2d'),image=ctx.createImageData(512,512),rng=seededRandom(4937);for(let y=0;y<512;y++)for(let x=0;x<512;x++){const i=(y*512+x)*4,strata=10*Math.sin(y*.105)+5*Math.sin(y*.027+x*.006),noise=(rng()-.5)*28,v=88+strata+noise;image.data[i]=v*1.02;image.data[i+1]=v*.94;image.data[i+2]=v*.82;image.data[i+3]=255}ctx.putImageData(image,0,0);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;t.wrapS=t.wrapT=THREE.RepeatWrapping;t.repeat.set(2.3,1.25);return t}
function makeCloudTexture(){const c=document.createElement('canvas');c.width=c.height=256;const ctx=c.getContext('2d'),rng=seededRandom(9384);for(let i=0;i<24;i++){const x=56+rng()*144,y=75+rng()*106,r=24+rng()*42,g=ctx.createRadialGradient(x,y,0,x,y,r);g.addColorStop(0,'rgba(255,255,255,.19)');g.addColorStop(.42,'rgba(244,250,252,.13)');g.addColorStop(1,'rgba(236,246,250,0)');ctx.fillStyle=g;ctx.fillRect(0,0,256,256)}const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;return t}
function seededRandom(seed){return()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296}}
function hash(text){return[...text].reduce((n,c)=>((n<<5)-n+c.charCodeAt(0))|0,0)>>>0}

function renderPeakList(){$('#selectedCount').textContent=`${selected.length} / ${MAX_PEAKS}`;$('#peakList').innerHTML=peaks.map(p=>`<label class="peak-row ${selected.includes(p.id)?'selected':''}"><input type="checkbox" data-peak="${p.id}" ${selected.includes(p.id)?'checked':''}><span class="peak-name"><b>${escapeHtml(p.name)}</b><small>${escapeHtml(p.region||'Coordonnées personnalisées')}</small></span><span class="peak-height">${p.elevation.toLocaleString('fr-CH')} m</span>${PEAKS.some(x=>x.id===p.id)?'':`<button class="delete-peak" data-delete="${p.id}" aria-label="Supprimer">×</button>`}</label>`).join('');
 document.querySelectorAll('[data-peak]').forEach(input=>input.addEventListener('change',()=>{if(input.checked&&selected.length>=MAX_PEAKS){input.checked=false;showError(`La composition accepte jusqu’à ${MAX_PEAKS} montagnes côte à côte.`);return}selected=input.checked?[...selected,input.dataset.peak]:selected.filter(id=>id!==input.dataset.peak);renderPeakList();rebuildScene()}));
 document.querySelectorAll('[data-delete]').forEach(button=>button.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();peaks=peaks.filter(p=>p.id!==button.dataset.delete);selected=selected.filter(id=>id!==button.dataset.delete);renderPeakList();rebuildScene()}))}

async function rebuildScene(){const version=++buildVersion;clearBlocks();const list=activePeaks();updateComparison(list);if(!list.length){hideLoading();showError('Sélectionne au moins un sommet pour créer une découpe.');return}hideError();showLoading('Construction des montagnes',`0 / ${list.length} découpe chargée`);const results=[];
 for(let i=0;i<list.length;i++){if(version!==buildVersion)return;$('#loadingDetail').textContent=`${i} / ${list.length} · téléchargement du relief et de la photo satellite`;try{const data=await loadPeakData(list[i],version);if(version!==buildVersion)return;const block=createBlock(data,list[i]);blocks.push(block);results.push(true);$('#loadingDetail').textContent=`${i+1} / ${list.length} découpe${list.length>1?'s':''} chargée${list.length>1?'s':''}`}catch(error){if(error.message==='cancelled')return;console.error(error);results.push(false);showError(`${list[i].name} n’a pas pu être construite : ${humanError(error)}`)}}
 if(version!==buildVersion)return;positionBlocks();buildGpxRoutes();createPeakLabels();fitCamera(false);hideLoading();if(results.some(Boolean)&&results.some(v=>!v))showError('Certaines découpes n’ont pas chargé. Vérifie la connexion puis change légèrement le diamètre pour réessayer.')}
function clearBlocks(){blocks.forEach(block=>{scene.remove(block.group);block.group.traverse(obj=>{obj.geometry?.dispose();if(obj.material&&obj.material!==sideMaterial){(Array.isArray(obj.material)?obj.material:[obj.material]).forEach(m=>{if(m.map!==cloudTexture)m.map?.dispose();m.dispose?.()})}})});blocks=[];$('#peakLabels').innerHTML=''}

async function loadPeakData(peak,version){const bounds=boundsAround(peak,patchKm);const[elevationCanvas,imageryCanvas]=await Promise.all([
 composeTiles(bounds,ELEVATION_ZOOM,320,(z,x,y)=>[`https://elevation-tiles-prod.s3.amazonaws.com/terrarium/${z}/${x}/${y}.png`],false),
 composeTiles(bounds,IMAGERY_ZOOM,768,(z,x,y)=>[`https://services.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/${z}/${y}/${x}`,`https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/${z}/${y}/${x}`],true)
 ]);if(version!==buildVersion)throw Error('cancelled');const pixels=elevationCanvas.getContext('2d',{willReadFrequently:true}).getImageData(0,0,elevationCanvas.width,elevationCanvas.height).data,heights=new Float32Array((GRID+1)*(GRID+1));for(let row=0;row<=GRID;row++)for(let col=0;col<=GRID;col++){const px=Math.min(elevationCanvas.width-1,Math.round(col/GRID*(elevationCanvas.width-1))),py=Math.min(elevationCanvas.height-1,Math.round(row/GRID*(elevationCanvas.height-1))),k=(py*elevationCanvas.width+px)*4;let h=pixels[k]*256+pixels[k+1]+pixels[k+2]/256-32768;if(!Number.isFinite(h)||h< -500)h=0;heights[row*(GRID+1)+col]=h}return{bounds,heights,textureCanvas:applyOrganicMask(imageryCanvas,hash(peak.id))}}
function boundsAround(peak,size){const half=size/2,dLat=half/110.574,dLon=half/(111.320*Math.cos(peak.lat*Math.PI/180));return{west:peak.lon-dLon,east:peak.lon+dLon,north:peak.lat+dLat,south:peak.lat-dLat}}
function lonLatToWorldPixel(lon,lat,zoom){const scale=2**zoom*TILE_SIZE,sin=Math.sin(Math.max(-85.0511,Math.min(85.0511,lat))*Math.PI/180);return{x:(lon+180)/360*scale,y:(.5-Math.log((1+sin)/(1-sin))/(4*Math.PI))*scale}}
async function composeTiles(bounds,zoom,size,urlFactory,smoothing){const nw=lonLatToWorldPixel(bounds.west,bounds.north,zoom),se=lonLatToWorldPixel(bounds.east,bounds.south,zoom),minX=Math.floor(nw.x/TILE_SIZE),maxX=Math.floor((se.x-1)/TILE_SIZE),minY=Math.floor(nw.y/TILE_SIZE),maxY=Math.floor((se.y-1)/TILE_SIZE),jobs=[];for(let y=minY;y<=maxY;y++)for(let x=minX;x<=maxX;x++)jobs.push({x,y,promise:loadImageWithFallback(urlFactory(zoom,x,y))});const loaded=await Promise.all(jobs.map(async j=>({...j,img:await j.promise}))),c=document.createElement('canvas');c.width=c.height=size;const ctx=c.getContext('2d');ctx.imageSmoothingEnabled=smoothing;if(smoothing)ctx.imageSmoothingQuality='high';const sx=size/(se.x-nw.x),sy=size/(se.y-nw.y);loaded.forEach(({x,y,img})=>ctx.drawImage(img,(x*TILE_SIZE-nw.x)*sx,(y*TILE_SIZE-nw.y)*sy,TILE_SIZE*sx,TILE_SIZE*sy));return c}
function loadImageWithFallback(urls){const key=urls.join('|');if(TILE_CACHE.has(key))return TILE_CACHE.get(key);const promise=(async()=>{let last;for(const url of urls)try{return await loadImage(url)}catch(e){last=e}throw last||Error('tile unavailable')})();TILE_CACHE.set(key,promise);promise.catch(()=>TILE_CACHE.delete(key));return promise}
function loadImage(url){return new Promise((resolve,reject)=>{const img=new Image();img.crossOrigin='anonymous';img.decoding='async';img.onload=()=>resolve(img);img.onerror=()=>reject(Error(`source inaccessible (${new URL(url).hostname})`));img.src=url})}
function organicOutline(seed,segments=128){const rng=seededRandom(seed),p1=rng()*Math.PI*2,p2=rng()*Math.PI*2,points=[];for(let i=0;i<segments;i++){const a=i/segments*Math.PI*2,r=.965+.018*Math.sin(a*3+p1)+.012*Math.sin(a*7+p2);points.push({x:Math.cos(a)*r,z:Math.sin(a)*r})}return points}
function applyOrganicMask(source,seed){const c=document.createElement('canvas');c.width=source.width;c.height=source.height;const ctx=c.getContext('2d');ctx.drawImage(source,0,0);const outline=organicOutline(seed);ctx.globalCompositeOperation='destination-in';ctx.beginPath();outline.forEach((p,i)=>{const x=(p.x*.5+.5)*c.width,y=(p.z*.5+.5)*c.height;i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.closePath();ctx.fill();return c}

function createBlock(data,peak){const group=new THREE.Group();group.name=peak.name;const geometry=createTopGeometry(data.heights),texture=new THREE.CanvasTexture(data.textureCanvas);texture.colorSpace=THREE.SRGBColorSpace;texture.anisotropy=Math.min(8,renderer.capabilities.getMaxAnisotropy());const material=new THREE.MeshStandardMaterial({map:texture,color:0xffffff,roughness:.94,metalness:0,alphaTest:.45}),top=new THREE.Mesh(geometry,material);top.castShadow=top.receiveShadow=shadowsEnabled;top.customDepthMaterial=new THREE.MeshDepthMaterial({depthPacking:THREE.RGBADepthPacking,map:texture,alphaTest:.45});group.add(top);const outline=organicOutline(hash(peak.id)),side=createSides(data.heights,outline);side.castShadow=side.receiveShadow=shadowsEnabled;group.add(side);const bottom=createBottom(outline);bottom.receiveShadow=true;group.add(bottom);const summitMarker=createSummitMarker(peak);group.add(summitMarker);const clouds=createClouds(peak);group.add(clouds);group.userData={peak,data,top,side,bottom,clouds,summitMarker,label:null};scene.add(group);return{group,peak,data}}
function createTopGeometry(heights){const positions=[],uvs=[],indices=[];for(let row=0;row<=GRID;row++)for(let col=0;col<=GRID;col++){const u=col/GRID,v=row/GRID;positions.push((u-.5)*patchKm,heights[row*(GRID+1)+col]/1000*exaggeration,(v-.5)*patchKm);uvs.push(u,1-v)}for(let row=0;row<GRID;row++)for(let col=0;col<GRID;col++){const a=row*(GRID+1)+col,b=a+1,c=a+GRID+1,d=c+1;indices.push(a,c,b,b,c,d)}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(positions,3));g.setAttribute('uv',new THREE.Float32BufferAttribute(uvs,2));g.setIndex(indices);g.computeVertexNormals();g.userData.heights=heights;return g}
function sampleGrid(heights,u,v){const x=Math.max(0,Math.min(GRID,u*GRID)),y=Math.max(0,Math.min(GRID,v*GRID)),x0=Math.floor(x),y0=Math.floor(y),x1=Math.min(GRID,x0+1),y1=Math.min(GRID,y0+1),tx=x-x0,ty=y-y0,h00=heights[y0*(GRID+1)+x0],h10=heights[y0*(GRID+1)+x1],h01=heights[y1*(GRID+1)+x0],h11=heights[y1*(GRID+1)+x1];return(h00*(1-tx)+h10*tx)*(1-ty)+(h01*(1-tx)+h11*tx)*ty}
function createSides(heights,outline){const positions=[],uvs=[],indices=[],n=outline.length;outline.forEach((p,i)=>{const x=p.x*patchKm/2,z=p.z*patchKm/2,u=p.x*.5+.5,v=p.z*.5+.5,top=sampleGrid(heights,u,v)/1000*exaggeration,s=i/n*5;positions.push(x,BASE_Y,z,x,top,z);uvs.push(s,0,s,1)});for(let i=0;i<n;i++){const next=(i+1)%n,a=i*2,b=a+1,c=next*2,d=c+1;indices.push(a,c,b,b,c,d)}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(positions,3));g.setAttribute('uv',new THREE.Float32BufferAttribute(uvs,2));g.setIndex(indices);g.computeVertexNormals();g.userData.outline=outline;g.userData.heights=heights;return new THREE.Mesh(g,sideMaterial)}
function createBottom(outline){const shape=new THREE.Shape();outline.forEach((p,i)=>i?shape.lineTo(p.x*patchKm/2,-p.z*patchKm/2):shape.moveTo(p.x*patchKm/2,-p.z*patchKm/2));shape.closePath();const mesh=new THREE.Mesh(new THREE.ShapeGeometry(shape),new THREE.MeshStandardMaterial({color:0x3a3933,roughness:1,side:THREE.DoubleSide}));mesh.rotation.x=-Math.PI/2;mesh.position.y=BASE_Y;return mesh}
function createSummitMarker(peak){const group=new THREE.Group();group.position.set(0,peak.elevation/1000*exaggeration+.025,0);const dot=new THREE.Mesh(new THREE.SphereGeometry(.065,16,10),new THREE.MeshBasicMaterial({color:0xffd18a})),halo=new THREE.Mesh(new THREE.RingGeometry(.09,.115,24),new THREE.MeshBasicMaterial({color:0x9ee6f6,transparent:true,opacity:.75,side:THREE.DoubleSide}));halo.rotation.x=-Math.PI/2;group.add(dot,halo);return group}
function createClouds(peak){const group=new THREE.Group(),rng=seededRandom(hash(peak.id)+117);group.name='clouds';for(let i=0;i<7;i++){const sprite=new THREE.Sprite(new THREE.SpriteMaterial({map:cloudTexture,transparent:true,opacity:.48+rng()*.18,depthWrite:false,color:0xf4fbff})),a=rng()*Math.PI*2,r=patchKm*(.12+rng()*.34);sprite.position.set(Math.cos(a)*r,1.4+rng()*1.65,Math.sin(a)*r);const scale=1.3+rng()*2.2;sprite.scale.set(scale*1.7,scale,1);sprite.userData={startX:sprite.position.x,phase:rng()*Math.PI*2,speed:.08+rng()*.1};group.add(sprite)}group.visible=$('#cloudToggle').checked;return group}
function positionBlocks(){const gap=Math.max(1,patchKm*.1),total=blocks.length*patchKm+(blocks.length-1)*gap;blocks.forEach((block,i)=>block.group.position.x=-total/2+patchKm/2+i*(patchKm+gap))}
function createPeakLabels(){$('#peakLabels').innerHTML='';blocks.forEach(block=>{const label=document.createElement('div');label.className='peak-label';label.innerHTML=`<span class="label-card"><b>${escapeHtml(block.peak.name)}</b><span>${block.peak.elevation.toLocaleString('fr-CH')} m</span></span>`;$('#peakLabels').appendChild(label);block.group.userData.label=label})}
function updatePeakLabels(){const width=stage.clientWidth,height=stage.clientHeight;blocks.forEach(block=>{const label=block.group.userData.label;if(!label)return;const v=new THREE.Vector3(block.group.position.x,block.peak.elevation/1000*exaggeration+.36,0).project(camera);label.style.left=`${(v.x*.5+.5)*width}px`;label.style.top=`${(-v.y*.5+.5)*height}px`;label.style.display=v.z>1?'none':''})}
function updateComparison(list=activePeaks()){if(!list.length){$('#comparisonBar').innerHTML='';return}const elevations=list.map(p=>p.elevation),delta=Math.max(...elevations)-Math.min(...elevations);$('#comparisonBar').innerHTML=list.map(p=>`<span class="comparison-peak"><b>${escapeHtml(p.name)}</b><span>${p.elevation.toLocaleString('fr-CH')} m</span></span>`).join('')+(list.length>1?`<span class="comparison-delta">écart maximal <strong>${delta.toLocaleString('fr-CH')} m</strong></span>`:'')}
function fitCamera(){const n=Math.max(1,blocks.length),gap=Math.max(1,patchKm*.1),width=n*patchKm+(n-1)*gap,aspect=Math.max(.45,stage.clientWidth/stage.clientHeight),vertical=patchKm*.72+5,vfov=THREE.MathUtils.degToRad(camera.fov),hfov=2*Math.atan(Math.tan(vfov/2)*aspect),distance=Math.max(vertical/(2*Math.tan(vfov/2)),width/(2*Math.tan(hfov/2)))*1.28;controls.target.set(0,1.35,0);camera.position.set(width*.12,Math.max(7,distance*.38),distance);camera.lookAt(controls.target);controls.update()}
function updateVerticalScale(){blocks.forEach(block=>{const position=block.group.userData.top.geometry.attributes.position,heights=block.data.heights;for(let i=0;i<heights.length;i++)position.setY(i,heights[i]/1000*exaggeration);position.needsUpdate=true;block.group.userData.top.geometry.computeVertexNormals();const sidePos=block.group.userData.side.geometry.attributes.position,outline=block.group.userData.side.geometry.userData.outline;outline.forEach((p,i)=>sidePos.setY(i*2+1,sampleGrid(heights,p.x*.5+.5,p.z*.5+.5)/1000*exaggeration));sidePos.needsUpdate=true;block.group.userData.side.geometry.computeVertexNormals();block.group.userData.summitMarker.position.y=block.peak.elevation/1000*exaggeration+.025});buildGpxRoutes()}

function parseGpx(text){const doc=new DOMParser().parseFromString(text,'application/xml');if(doc.querySelector('parsererror'))throw Error('Le fichier GPX est invalide.');const points=[...doc.querySelectorAll('trkpt,rtept')].map(node=>({lat:+node.getAttribute('lat'),lon:+node.getAttribute('lon'),ele:Number(node.querySelector('ele')?.textContent)})).filter(p=>Number.isFinite(p.lat)&&Number.isFinite(p.lon));if(points.length<2)throw Error('Aucune trace exploitable dans ce GPX.');let distance=0,gain=0;for(let i=1;i<points.length;i++){const a=points[i-1],b=points[i],dLat=(b.lat-a.lat)*Math.PI/180,dLon=(b.lon-a.lon)*Math.PI/180,h=Math.sin(dLat/2)**2+Math.cos(a.lat*Math.PI/180)*Math.cos(b.lat*Math.PI/180)*Math.sin(dLon/2)**2;distance+=12742*Math.asin(Math.sqrt(h));if(Number.isFinite(a.ele)&&Number.isFinite(b.ele)&&b.ele>a.ele)gain+=b.ele-a.ele}return{points,distance,gain}}
function buildGpxRoutes(){blocks.forEach(block=>{const old=block.group.getObjectByName('gpx-route');if(old){block.group.remove(old);old.geometry.dispose();old.material.dispose()}if(!gpxTrack.length)return;let pts=gpxTrack.filter(p=>p.lon>=block.data.bounds.west&&p.lon<=block.data.bounds.east&&p.lat>=block.data.bounds.south&&p.lat<=block.data.bounds.north);if(pts.length<2)return;const stride=Math.max(1,Math.ceil(pts.length/900));pts=pts.filter((_,i)=>i%stride===0||i===pts.length-1);const coords=pts.map(p=>{const u=(p.lon-block.data.bounds.west)/(block.data.bounds.east-block.data.bounds.west),v=(block.data.bounds.north-p.lat)/(block.data.bounds.north-block.data.bounds.south),h=Number.isFinite(p.ele)?p.ele:sampleGrid(block.data.heights,u,v);return new THREE.Vector3((u-.5)*patchKm,h/1000*exaggeration+.055,(v-.5)*patchKm)}),geometry=new THREE.BufferGeometry().setFromPoints(coords),material=new THREE.LineBasicMaterial({color:0x51e5ff,depthTest:true,transparent:true,opacity:.98}),line=new THREE.Line(geometry,material);line.name='gpx-route';line.renderOrder=4;block.group.add(line)})}

function bindControls(){$('#patchSize').addEventListener('input',e=>{$('#patchSizeValue').value=`${e.target.value} km`;patchKm=+e.target.value;clearTimeout(rebuildTimer);rebuildTimer=setTimeout(rebuildScene,350)});$('#exaggeration').addEventListener('input',e=>{exaggeration=+e.target.value;$('#exaggerationValue').value=`${exaggeration.toFixed(1).replace('.',',')}×${exaggeration===1?' réelle':''}`;$('.scale-badge').innerHTML=`<i></i><b>Même échelle</b> · relief ${exaggeration.toFixed(1).replace('.',',')}×`;updateVerticalScale()});$('#cloudToggle').addEventListener('change',e=>blocks.forEach(b=>b.group.userData.clouds.visible=e.target.checked));$('#shadowToggle').addEventListener('change',e=>{shadowsEnabled=e.target.checked;renderer.shadowMap.enabled=shadowsEnabled;blocks.forEach(b=>{b.group.userData.top.castShadow=b.group.userData.top.receiveShadow=shadowsEnabled;b.group.userData.side.castShadow=shadowsEnabled})});$('#rotateButton').addEventListener('click',()=>{controls.autoRotate=!controls.autoRotate;$('#rotateButton').classList.toggle('active',controls.autoRotate)});$('#resetCameraButton').addEventListener('click',fitCamera);$('#filmButton').addEventListener('click',()=>{document.body.classList.toggle('film-mode');setTimeout(()=>{resize();fitCamera()},80);if(document.body.classList.contains('film-mode'))document.documentElement.requestFullscreen?.().catch(()=>{})});$('#menuButton').addEventListener('click',()=>setPanel(!document.body.classList.contains('panel-open')));$('#closePanelButton').addEventListener('click',()=>setPanel(false));$('#panelScrim').addEventListener('click',()=>setPanel(false));
 $('#addPeakButton').addEventListener('click',()=>$('#peakDialog').showModal());$('#confirmPeakButton').addEventListener('click',e=>{const peak={id:`custom-${Date.now()}`,name:$('#newName').value.trim(),elevation:+$('#newElevation').value,lat:+$('#newLat').value,lon:+$('#newLon').value,region:'Sommet personnalisé'};if(!peak.name||peak.elevation<=0||!Number.isFinite(peak.lat)||!Number.isFinite(peak.lon)){e.preventDefault();return}peaks.push(peak);if(selected.length<MAX_PEAKS)selected.push(peak.id);renderPeakList();rebuildScene();$('#peakForm').reset()});$('#gpxInput').addEventListener('change',e=>handleGpxFile(e.target.files[0]));const drop=$('#dropZone');['dragenter','dragover'].forEach(type=>drop.addEventListener(type,e=>{e.preventDefault();drop.classList.add('dragging')}));['dragleave','drop'].forEach(type=>drop.addEventListener(type,e=>{e.preventDefault();drop.classList.remove('dragging')}));drop.addEventListener('drop',e=>handleGpxFile(e.dataTransfer.files[0]));$('#saveButton').addEventListener('click',saveStats);window.addEventListener('resize',resize);document.addEventListener('fullscreenchange',()=>{if(!document.fullscreenElement)document.body.classList.remove('film-mode');setTimeout(resize,50)})}
async function handleGpxFile(file){if(!file)return;try{const r=parseGpx(await file.text());gpxTrack=r.points;$('#distance').value=r.distance.toFixed(1);$('#gain').value=Math.round(r.gain);$('#gpxStats').textContent=`${r.points.length.toLocaleString('fr-CH')} points · ${r.distance.toFixed(1)} km · +${Math.round(r.gain).toLocaleString('fr-CH')} m`;$('#gpxStats').classList.add('loaded');buildGpxRoutes();if(!blocks.some(block=>gpxTrack.some(p=>p.lon>=block.data.bounds.west&&p.lon<=block.data.bounds.east&&p.lat>=block.data.bounds.south&&p.lat<=block.data.bounds.north)))showError('Le GPX est chargé, mais son tracé ne traverse aucune découpe actuellement affichée.')}catch(e){showError(e.message)}}
function saveStats(){const ids=['distance','gain','duration','date','notes'];localStorage.setItem('mountainAnimatorStats',JSON.stringify(Object.fromEntries(ids.map(id=>[id,$('#'+id).value]))));const b=$('#saveButton');b.textContent='✓ Enregistré';setTimeout(()=>b.textContent='Enregistrer sur cet appareil',1500)}
function restoreStats(){try{const data=JSON.parse(localStorage.getItem('mountainAnimatorStats')||'{}');Object.entries(data).forEach(([id,v])=>{if($('#'+id))$('#'+id).value=v})}catch{}}
function setPanel(open){document.body.classList.toggle('panel-open',open);$('#menuButton').setAttribute('aria-expanded',String(open))}
function showLoading(title,detail){$('#loadingPanel').hidden=false;$('#loadingTitle').textContent=title;$('#loadingDetail').textContent=detail}
function hideLoading(){$('#loadingPanel').hidden=true}function showError(message){const p=$('#errorPanel');p.textContent=message;p.hidden=false;clearTimeout(showError.timer);showError.timer=setTimeout(hideError,8500)}function hideError(){$('#errorPanel').hidden=true}
function humanError(){return!navigator.onLine?'aucune connexion Internet':'les données de relief ou l’imagerie sont temporairement inaccessibles'}
function escapeHtml(value){return String(value).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function resize(){const width=stage.clientWidth,height=stage.clientHeight;if(!width||!height)return;renderer.setSize(width,height,false);camera.aspect=width/height;camera.updateProjectionMatrix()}
const clock=new THREE.Clock();function animate(){requestAnimationFrame(animate);const t=clock.getElapsedTime();controls.update();blocks.forEach(block=>block.group.userData.clouds.children.forEach(sprite=>{sprite.position.x=sprite.userData.startX+Math.sin(t*sprite.userData.speed+sprite.userData.phase)*.22}));updatePeakLabels();renderer.render(scene,camera)}
